Be detailed card #2
hatchways/team-metamorphic pull request #38
Opened 2021-10-28 16:31 UTC by uche-okoroafor

### What this PR does (required):
 BE- detailed card   #2 
- Create methods for handling adding and removing sections of a card.

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**
![Screenshot (140)](https://user-images.githubusercontent.com/71725892/139294802-55befe98-88b1-4254-825c-32e8533e6999.png)
![Screenshot (141)](https://user-images.githubusercontent.com/71725892/139294899-b2d5a812-c41e-44de-9c06-1d28de987299.png)

![Screenshot (142)](https://user-images.githubusercontent.com/71725892/139294928-610b0fb4-1691-4555-ad86-44ed7dbae564.png)

![Screenshot (143)](https://user-images.githubusercontent.com/71725892/139294965-60146222-7b33-40fd-9060-05436289abd6.png)

![Screenshot (144)](https://user-images.githubusercontent.com/71725892/139295016-e0db32ed-00f9-4b43-b6e0-ae02aedb02d3.png)

![Screenshot (145)](https://user-images.githubusercontent.com/71725892/139295495-c9438de1-a071-4f92-a49f-581f029afa58.png)

![Screenshot (146)](https://user-images.githubusercontent.com/71725892/139295523-e70599d5-c1b8-46b6-bbb1-355d18105581.png)

### Any information needed to test this feature (required):

- Use a PostMan app or Insomnia to make a request to the routes inside the "routes" directory.

- Also remove the " protect" function that checks for cookies in the address of the route.

### Any issues with the current functionality (optional):

- I had an issue with removing fields in the card, I was unable to find a MongoDB operation that can remove fields in a deep array, so I had to use Javascript to get the index and later applied it to a MongoDB operation and it worked, please if there is any better way to do it will be very good.

2021-11-01 16:42 UTC, ababber commented
Good job so far Uche! I was looking at the schema for cards and columns, and I was wondering how you would link each card/task to each column? I'm in the middle of working on the drag and drop feature for cards and columns, and one of the things that set me back was not planning my local data template to accommodate which card is associated with which column, do you think we will need to do that on the back end as well?  For example, here is a local data template I am using on the front end:

`const defaultData: BoardData = {
  tasks: {
    'task-1': { id: 'task-1', title: 'task 1' },
  },
  uniqueTaskKey: 2,
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Not Started',
      taskIds: [''],
    },
    'column-2': {
      id: 'column-2',
      title: 'In Progress',
      taskIds: ['task-1'],
    },
    'column-3': {
      id: 'column-3',
      title: 'Completed',
      taskIds: [''],
    },
  },
  uniqueColumnKey: 4,
  columnOrder: ['column-1', 'column-2', 'column-3'],
};`

2021-11-01 18:41 UTC, moffatethan commented on server/models/Card.js
> +  },
This doesn't need to be here, Mongo will generate an id on this by default.

2021-11-02 14:56 UTC, moffatethan requested changes
Hey good work so far, 

My only concern right now is if the base of the branch is correct & we have no route for getting the card details. 

Also, as discussed in sprint planning we are going a different direction on the card actions which is fine to keep the code on check-lists as we can likely re-use that. 😄

2021-11-02 14:56 UTC, moffatethan commented on server/controllers/checklist.js
> +    res.status(400);
Hey, let's actually keep this here for when we implement our plugins. We can re-use this 😄

2021-11-02 14:56 UTC, moffatethan commented on server/models/Card.js
> +    required: false
`required: false` is the default behaviour of Mongoose. We don't need to explicitly define it. Please change where applicable.

2021-11-02 14:56 UTC, moffatethan commented on server/models/Card.js
> +      },
If we're doing a reference store which we will with plugins this will not be needed.

2021-11-05 22:52 UTC, moffatethan requested changes
Please remove dist files, unnecessary controllers for checklists and image uploads. Keep the cloudinary setup though so we have it. But please be aware of current discussions that we've had in standups 😄

2021-11-05 22:52 UTC, moffatethan commented on server/config/cloudinaryConfig.js
> +};
Not sure why this is here? It's not related to the detailed card work.

2021-11-05 22:52 UTC, moffatethan commented on server/config/multerConfig.js
> +    if (file.mimetype === "image/jpeg" || file.mimetype === "image/png") {
Same here

2021-11-05 22:52 UTC, moffatethan commented on server/controllers/card.js
> +        "boards.$[board].columns.$[column].cards.$[card].checklists": {
As mentioned many times, this is actually not needed. We are doing a different approach so we can remove this code. Please make sure to be aware of what we're doing in the project going forward so we aren't spending time on unnecessary changes 👍🏻

2021-11-09 20:14 UTC, moffatethan requested changes
Please address merge conflicts

2021-11-10 18:02 UTC, moffatethan approved these changes

2021-11-11 10:32 UTC, merged