Setup cloudinary #26
hatchways/team-metamorphic pull request #44
Opened 2021-11-02 10:08 UTC by uche-okoroafor

### What this PR does (required):
Setup Cloudinary   #26 
- Allow for uploading of images 

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**

https://user-images.githubusercontent.com/71725892/139826769-aaa646c2-8a70-4b23-9806-230d3197081d.mp4

### Any information needed to test this feature (required):
- In your postman or Insomnia, you will need to create a POST request to http://localhost:3001/image/upload
- In the request body you should select form-data and add "imageName" as the key name and select an image file.    
- If the image is uploaded successfully, you can check the response from the postman.

2021-11-02 11:02 UTC, ezeilo-su reviewed
Good work with this one :+1:  I've left a few nice-to-have comments for you to take a look at.

2021-11-02 11:02 UTC, ezeilo-su commented on server/controllers/image.js
> +        });
Please consider using `async/await` to be more readable.

2021-11-02 11:08 UTC, ezeilo-su requested changes
Please take a look at those comments :+1:

2021-11-02 11:08 UTC, ezeilo-su commented on server/routes/image.js
> +);
This should be a protected route. Use the `protect` middleware.

2021-11-09 21:04 UTC, moffatethan requested changes
Please address merge conflicts!

2021-11-10 18:03 UTC, moffatethan approved these changes

2021-11-12 16:15 UTC, moffatethan commented
@uche-okoroafor Please merge this in!

2021-11-12 16:39 UTC, merged