FE- calendar #8
hatchways/team-metamorphic pull request #59
Opened 2021-11-07 14:16 UTC by uche-okoroafor

### What this PR does (required):
-  Closes #8 
- Displays a big Calendar that contains cards with titles, tag color, and deadlines.
- The cards can be dragged to change the deadline.
### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**

https://user-images.githubusercontent.com/71725892/140648535-b807cc09-9b36-4bc7-bf63-86c4a16fcaee.mp4

### Any information needed to test this feature (required):
Run the messenger app,login and go to http://localhost:3000/calendar

2021-11-08 14:15 UTC, ezeilo-su requested changes
Nice work on this one :+1:  Just go through the few comments I left and address them.

2021-11-08 14:15 UTC, ezeilo-su commented on server/controllers/dist/auth.dev.js
> +}); // @route POST /auth/login
Break this documentation into the next line

2021-11-08 14:15 UTC, ezeilo-su commented on server/controllers/dist/auth.dev.js
> +}); // @route GET /auth/user
The same thin here as the previous comment

2021-11-12 16:40 UTC, moffatethan requested changes

2021-11-12 16:40 UTC, moffatethan commented on package.json
> +    "react-big-calendar": "^0.38.0"
Is this installed in the root directory? It should be installed in the client package file.

2021-11-12 16:40 UTC, moffatethan commented
Just that change there and the merge conflicts please. 👍🏻

2021-11-17 18:12 UTC, moffatethan approved these changes

2021-11-17 18:18 UTC, merged