completed card cover schema & instance methods
hatchways/team-metamorphic pull request #62
Opened 2021-11-12 05:56 UTC by refugedesigns

### What this PR does (required):
- This is the card cover plugin for adding a cover image to a card

### Screenshots / Videos (front-end only):
- N/A

### Any information needed to test this feature (required):
- create routes and controllers for card cover image to test method instance
- Method instance created: get, create, update, delete

2021-11-12 13:26 UTC, ezeilo-su reviewed
Looks good! Please always link your ticket in any PR you create. (see this [guide])(https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Filling the PR template and linking the issue you're addressing is an important requirement here.
Happy coding!

2021-11-12 14:19 UTC, refugedesigns commented
> Looks good! Please always link your ticket in any PR you create. See this [guide](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). Filling the PR template and linking the issue you're addressing is an important requirement here. Happy coding!

PR template filled and linked to create CardCoverPlugin/CardCoverPluginSchema - #52

2021-11-12 16:54 UTC, moffatethan requested changes

2021-11-12 16:54 UTC, moffatethan commented on server/models/CardCoverPlugin.js
> +  return await this.model("CardCoverPlugin").findById(params.coverId)
So, we're actually going to be enforcing a response structure. 

`{  status code, data/message }`

200 responses should be the following `{ response: 200, data: <Cover data> }`
Anything else -> `{  response: XXX, message: "Any message" }`

2021-11-12 16:54 UTC, moffatethan commented on server/models/CardCoverPlugin.js
> +  return await this.model("CardCoverPlugin").findById(params.coverId)
Please update in all your action handlers.

2021-11-18 04:13 UTC, moffatethan requested changes

2021-11-18 04:13 UTC, moffatethan commented on client/src/components/DropZone/DropZone.tsx
> +      console.log(acceptedFile);
We can remove the console log here

2021-11-18 04:13 UTC, moffatethan commented on server/models/BasePlugin.js
> +);
So, Peter has updated his branch so we should update this too

2021-11-18 18:03 UTC, moffatethan approved these changes

2021-11-19 05:00 UTC, merged