BE: Create CardChecklistPlugin / ChecklistSchema
hatchways/team-metamorphic pull request #63
Opened 2021-11-12 10:46 UTC by uche-okoroafor

BE: Create CardChecklistPlugin /ChecklistSchema  #50 

### What this PR does (required):
 - it can  create, get, update, patch, and delete a checklist using the Cardchecklist plugin and checklist schema   

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

2021-11-12 14:39 UTC, ezeilo-su reviewed
LGTM!

2021-11-12 16:56 UTC, moffatethan requested changes

2021-11-12 16:56 UTC, moffatethan commented on server/models/Checklist.js
> +  throw new Error("something went wrong");
I would rather have this respond with a new status code or 500. 

`{ response: 400, message }`

2021-11-12 16:56 UTC, moffatethan commented on server/models/Checklist.js
> +  throw new Error("something went wrong");
Please update where applicable in the action handlers.

2021-11-15 17:28 UTC, moffatethan requested changes

2021-11-15 17:28 UTC, moffatethan commented on server/models/Checklist.js
> +  }
We should be responding with an object

`{ response: XXX, message: "" }`

Please address where applicable

2021-11-18 04:14 UTC, moffatethan requested changes

2021-11-18 04:14 UTC, moffatethan commented on server/controllers/dist/check.dev.js
> +  var user;
Please remove the built code from the PR

2021-11-18 18:03 UTC, moffatethan approved these changes

2021-11-19 01:57 UTC, moffatethan reviewed
**Please address merge conflicts before merge**

2021-11-19 03:30 UTC, merged