FE: Detailed Card #18
hatchways/team-metamorphic pull request #70
Opened 2021-11-16 06:53 UTC by uche-okoroafor

FE: Detailed Card #18

### What this PR does (required):
-User interface for Card details #18 
-User can add, edit or remove items from the Card

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**

https://user-images.githubusercontent.com/71725892/141935778-3ee71caf-7e7e-4a3b-9cf0-7d0ac8e2d51b.mp4

### Any information needed to test this feature (required):
- Post what steps to take to be able to test this feature (eg. "sign up as a new user and upload a profile picture from the navbar")

### Any issues with the current functionality (optional):
- List any problems where you were not able to complete all tasks on ticket
- List any problems this PR may cause for the project or other active PRs
- Post a screenshot/video of the problem, along with detailed console outputs where applicable

2021-11-16 10:12 UTC, ezeilo-su commented
Please resolve the merge conflict in this branch

2021-11-16 12:37 UTC, ezeilo-su requested changes
Hey @uche-okoroafor, you've done good work here. I've left you a couple of comments to address, though :smile:

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/mocks/mockCard.ts
> +// ];
Please let's get rid of this unused code block.

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/Board.tsx
> +      // console.log(boards, 'boards');
Let's remove this comment from here

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/Board.tsx
> +        // SetDisplayedBoard(boards[0]);
Remove this one too

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/Board.tsx
> +    console.log(boards);
Please remove console log :smile:

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardAttachment.tsx
> +// import { saveAttachment, deleteAttachment } from '../../../helpers/APICalls/cardApiCalls';
Let's remove this comment line

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardAttachment.tsx
> +    // } catch (err) {}
Get rid of these comments

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardAttachment.tsx
> +    // } catch (err) {}
Remove this one too

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardAttachment.tsx
> +    console.log(e.target.files);
We don't need this one. Please remove.

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardChecklist.tsx
> +// import { saveListItem, checkItem, deleteList } from '../../../helpers/APICalls/cardApiCalls';
Remove this comment line

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardChecklist.tsx
> +    // } catch (err) {}
Let's get rid of this comment block

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardChecklist.tsx
> +    //   } catch (err) {}
This one too

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardChecklist.tsx
> +    //   } catch (err) {}
This one too

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardComment.tsx
> +        // updateSnackBarMessage(data.error.message);
Please remove comment

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardComment.tsx
> +        // updateSnackBarMessage('An unexpected error occurred. Please try again');
Let's also remove this one

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardComment.tsx
> +        // updateCardContext(data.success);
Also get rid of this one

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardDeadline.tsx
> +        // updateSnackBarMessage(data.error.message);
Remove

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardDeadline.tsx
> +        // should not get here from backend but this catch is for an unknown issue
Please remove

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardDeadline.tsx
> +        // updateSnackBarMessage('An unexpected error occurred. Please try again');
Remove

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardDeadline.tsx
> +        // should not get here from backend but this catch is for an unknown issue
Please remove

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardDescription.tsx
> +        // updateSnackBarMessage(data.error.message);
Remove comment

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardDescription.tsx
> +        // updateSnackBarMessage('An unexpected error occurred. Please try again');
Also remove this one

2021-11-16 12:37 UTC, ezeilo-su commented on client/src/pages/Board/CardDialogComponents/CardDescription.tsx
> +        // updateCardContext(data.success);
This comment is not needed. Please remove.

2021-11-16 12:37 UTC, ezeilo-su commented on server/controllers/board.js
> +});
Did you combine two tickets here? This one is a backend code.

2021-11-16 12:43 UTC, ezeilo-su commented
Please resolve this merge conflict

2021-11-18 04:17 UTC, moffatethan approved these changes

2021-11-18 04:37 UTC, merged