FE- build the card checklist plugin #54
hatchways/team-metamorphic pull request #71
Opened 2021-11-17 15:57 UTC by uche-okoroafor

FE- build the card checklist plugin   #54  

### What this PR does (required):
-Adds checklist to the database

### Screenshots / Videos (front-end only):
- Post at least one screenshot to show the feature in action. **Only required in front-end work**

https://user-images.githubusercontent.com/71725892/142235011-c28ca557-a893-4cc5-8b03-d6693309711e.mp4

2021-11-17 17:11 UTC, ezeilo-su requested changes
Hey @uche-okoroafor, great job here. Please check the comments below and make the required changes :+1:

2021-11-17 17:11 UTC, ezeilo-su commented on client/src/components/Kanban/Card/CardDetails/CardDetailsComponents/CardDescription.tsx
> +        // updateCardContext(data.success);
Yet to implement this?

2021-11-17 17:11 UTC, ezeilo-su commented on server/controllers/board.js
> +
Did you intentionally include this in this ticket?

2021-11-19 01:57 UTC, moffatethan approved these changes

2021-11-19 03:35 UTC, merged